# Generated by Django 5.0.6 on 2024-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='waiting', max_length=10),
        ),
    ]
