# Generated by Django 5.0.6 on 2024-08-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_mcqs'),
        ('mcqs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mcqs',
        ),
        migrations.AddField(
            model_name='game',
            name='mcqs',
            field=models.ManyToManyField(to='mcqs.mcq'),
        ),
    ]
